# Generated by Django 5.0.4 on 2024-04-14 22:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='description',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='date',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='diary_name',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='time',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='date',
        ),
        migrations.AddField(
            model_name='diary',
            name='isLocked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='password',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diary',
            name='username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='dateCreated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='diary',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='diary.diary'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
